# Site settings
title: Hublr.
email: hublr@outlook.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/hublr" 
url: "burks10.github.io" 

twitter_username:
github_username: burks10

# Build settings
markdown: kramdown
