# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Homepage of Anthony Burkholder
email: anthony.burkholder.10@gmail.com
author: Anthony Burkholder
author_firstname: Anthony
author_lastname: Burkholder
description: > # My name is Anthony Burkholder. I'm a final year Computer
              Engineering student who loves to create new things and solve
              challenging problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anthonyb.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  burks10

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
