baseURL = "https://burks.page"
languageCode = "en-us"
title = "Burks Page"
theme = "novela"
paginate = 6
enableRobotsTXT = true
canonifyURLs = true
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "about"
    Name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
  tag = "tags"
  author = "authors"
  preserveTaxonomyNames = true


[permalinks]
  post = "/blog/:title/"
  